# Generated by Django 5.1.4 on 2024-12-12 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_reviewrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='reviewrating',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
